Shade-Heart/graceshopper

server/db/models/user.js
=> Model: Adds Email Validation

package.json
=> Precommit # removed

server/db/models/index.js, server/db/models/reviews.js
=> adds reviews model, updates index to include associations

server/db/models/hats.js
=> Model Hats pluralization

server/db/models/index.js, server/db/models/orders.js
=> added order model and fixed association naming in index

server/api/users.spec.js, server/db/models/user.js, server/db/models/user.spec.js
=> Tests: All passing

server/api/index.js, server/api/reviews.js
=> Problem branch

client/components/SingleHat.js, server/db/models/hats.js, server/db/models/user.js
=> Images now render

client/components/SmallForm.js, client/components/auth-form.js, client/components/user-home.js, client/store/user.js, server/auth/google.js, server/db/models/user.js
=> with login and signup including Google authentication and update in welcome page

server/api/hats.spec.js
=> added tests for findALL, findByID, and Post in the hats routes

client/components/AllHats.js
=> completed search function

server/api/reviews.js, server/api/reviews.spec.js, server/db/models/reviews.js
=> 47 review routes tests

client/components/AddHat.js
=> Added rop-down menus for sizes and categories

client/components/AllHats.js, server/api/authentication-middleware.js, server/api/hats.js, server/api/hats.spec.js, server/api/reviews.js, server/api/reviews.spec.js, server/api/users.js, server/api/users.spec.js
=> Authentication middleware

client/components/Welcome.js, client/components/user-home.js, client/routes.js
=> Created Welcome page

client/components/AddHat.js, client/components/AllHats.js, client/components/AllHatsContainer.js, client/components/EditHat.js, client/components/SingleHat.js, client/components/SingleHatContainer.js, client/store/user.js
=> ternarys working

client/components/AllHats.js
=> filter by category

client/components/AllHats.js, script/seed.js, server/db/models/hats.js
=> updated seed data

client/components/AddToCart.js, client/components/Cart.js, client/components/SingleHat.js, client/components/user-home.js, client/routes.js, client/store/cartReducer.js, client/store/index.js, client/store/lineItem.js, client/store/orderReducer.js, package-lock.json, public/style.css, server/api/order-hat.js, server/db/models/orderHat.js, server/db/models/orders.js
=> Render cart

client/components/Cart.js
=> cart now links back to single item and is rendered as a table

client/components/MyAccount.js, client/components/SingleHat.js
=> remove unnecessary checkout from components

client/components/AllHats.js, client/components/navbar.js, package-lock.json, package.json, public/index.html
=> added semantic to navbar and all products components

client/components/AddToCart.js, client/components/Cart.js, client/store/lineItem.js, public/style.css, server/api/order-hat.js
=> Remove cart

public/style.css
=> fixes alignment of headers for cart

client/components/AddToCart.js, client/components/SingleHat.js, public/style.css
=> single hat  page styled

client/components/AddToCart.js, client/components/Cart.js, client/components/EditHat.js, client/components/SingleHat.js, client/components/user-home.js, client/store/orderReducer.js, server/api/orders.js, server/db/models/orders.js
=> Huge cart bug fix

client/components/Cart.js
=> fix remove button

client/components/Cart.js, client/components/Checkout.js, client/components/CheckoutForm.jsx, client/components/navbar.js, client/routes.js
=> set up checkout route

client/components/Cart.js, client/components/Welcome.js, client/components/navbar.js, client/components/user-home.js, client/components/user-home.spec.js, public/style.css, server/api/hats.spec.js
=> styled nav bar and welcome page

client/components/AddToCart.js, client/components/AllHats.js, client/components/Cart.js, client/components/Checkout.js, client/components/CheckoutForm.jsx, client/components/MyAccount.js, client/components/user-home.js, public/style.css, server/api/orders.js, server/db/models/orders.js
=> oid bug fix

client/components/AddToCart.js, client/components/AllHats.js, client/components/Cart.js, client/components/MyAccount.js, client/components/user-home.js, server/api/orders.js
=> Oid bugfix

client/components/MyAccount.js, client/components/navbar.js
=> fix rendering account issue

server/api/users.spec.js
=> made user api test to test for authorization access

client/components/MyAccount.js
=> order history renders unique orders #s and displays date of purchase

client/components/AddToCart.js, client/components/Cart.js, client/components/Welcome.js, client/store/orderReducer.js, client/store/user.js, server/api/orders.js, server/auth/index.js, server/db/models/user.js
=> guest cart feature working

client/store/allHatsReducer.spec.js
=> Add all hats store test

server/api/order-hat.js, server/api/orders.js
=> protected routes

client/components/navbar.js, public/style.css
=> guest styled

client/components/AddHat.js, client/components/AddToCart.js, client/components/AllHats.js, client/components/Cart.js, client/components/MyAccount.js, client/components/Welcome.js, client/components/user-home.js, client/store/user.js, server/api/order-hat.js, server/api/orders.js
=> un-protected routes

client/components/AddHat.js, client/components/EditHat.js, client/components/MyAccount.js
=> feature edit hat
